### ISSUE TITLE
Gear Seems to lag

### ISSUE THREAD

**Issue by AlexGellert** [TheStonedTurtle/party-panel#17]
Hey I noticed the Gear doesn't always update unless people leave and rejoin the party.
Can you add a refresh button that will re-grab everyones info hopefully fixing this issue.

I was going to create a PR myself but I can't seem to get your plugin to load in my runelite environment.
(relatively new to runelite development)

**Comment by TheStonedTurtle** [comment]
This is most likely an issue that was introduced in f9df7ec22be557a9bef4c64221eda42596865b6a. 

Is it just the gear that doesn't always update or is it other tabs as well? Have you found any way to replicate the issue?

I'd like to avoid adding a refresh button as it would transmit a lot of data at once and the RL team wants us to minimize the data we transfer since they pay for the server that transmits it between clients.

**Comment by AlexGellert** [comment]
I'll try and get some better steps to reproduce for you.

**Comment by AlexGellert** [comment]
Steps to reproduce:
1. login to a runescape account
2. login a second one
3. Have both join the party
4. change the inventory of one account

You could implement something like a debouncer so you aren't constantly spamming the API. Have it to be triggered once a minute if a change happens or add a refresh button with a lock that can be triggered once every 5 minutes manually. 

If people are leaving and rejoining the party quickly this 'hacky' way around the bug will trigger more API calls in the long term i'd assume.

**Comment by TheStonedTurtle** [comment]
I believe I fixed in this 61eeeeb7c2fd70ebc57639a1ef38f810f8df0aca, it seems like the issue was that on the initial expansion of a user their inventory would never update unless you switched to a new tab and then back to it.
